name: FightToSurvive
main: me.bukkit.Infernaton.FightToSurvive
version: 1.3
commands:
  start:
    description: start the game
    usage: /start
  cancelStart:
    description: to cancel when the game is about to start
    usage: /cancelStart
  reset:
    description: to reset a started game
    usage: /reset
  forceFinal:
    description: In game, force the final Phase to begin
    usage: /forceFinal
  setPlayer:
    description: Debug when a player is in the wrong gamemode
    usage: /setPlayer <player>
    permission: test.use
  getDoors:
    description: set all doors at location
    usage: /getDoors
  deleteDoors:
    description: delete all doors at location
    usage: /deleteDoors
  getKey:
    description: get a key to open a door
    usage: /<command>
  printDebug:
    description: to debug some behaviour
    usage: /<command>
  mob_zombie:
    description: Spawn a zombie near to the player
    usage: /<command> <level?>
  set_villagers:
    description: spawn all villager
    usage: /<command>
  kill_pnj:
    description: kill pnj
    usage: /<command>
  hologram:
    description: create a custom displayed text in the world
    usage: /<command> <text>
  killhologram:
    description: remove the next nearby hollogram
    usage: /<command>