name: FightToSurvive
main: me.bukkit.Infernaton.FightToSurvive
version: 1.4
commands:
  start:
    description: start the game
    usage: /start
  cancelStart:
    description: to cancel when the game is about to start
    usage: /cancelStart
  setPlayer:
    description: Debug when a player is in the wrong gamemode
    usage: /setPlayer <player>
    permission: test.use
  trade:
    description: open trade
    usage: /<command>
  mob:
    description: spawn villager
    usage: /<command>
