name: FightToSurvive
main: me.bukkit.Infernaton.FightToSurvive
version: 1.0
commands:
  hello:
    description: It replies
    usage: /<command>
  reset:
    description: It reset the game
    usage: /<command>