name: FightToSurvive
main: me.bukkit.Infernaton.FightToSurvive
version: 1.5
commands:
  start:
    description: start the game
    usage: /start
  cancelStart:
    description: to cancel when the game is about to start
    usage: /cancelStart
  reset:
    description: to reset a started game
    usage: /reset
  setPlayer:
    description: Debug when a player is in the wrong gamemode
    usage: /setPlayer <player>
    permission: test.use
  mob_villager:
    description: spawn villager with wood tools trade
    usage: /<command>
  manage_time:
    description: manage time switch
    usage: /<command>
  getDoor:
    description: set a door at location
    usage: /getDoor
  getDoors:
    description: set all doors at location
    usage: /getDoors
  deleteDoors:
    description: delete all doors at location
    usage: /deleteDoors


