name: FightToSurvive
main: me.bukkit.Infernaton.FightToSurvive
version: 1.0
commands:
  hello:
    description: It replies
    usage: /<command>
  setPlayer:
    description: To play the game
    usage: /<command> <player>
    permission: test.use
  trade:
    description: open trade
    usage: /<command>
  mob:
    description: spawn villager
    usage: /<command>
